layout_spectrum: 0.3086724
typography_spectrum: 0.587234
color:
  saturation: 0.6553192
  brandStrength: 0.8833569
  lightness: 0.4302831
  rhythmicContrast: 0.7181242
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: TestV2
